#! /bin/sh

# Other deployment actions here. Want to install (or bounce) service last.

#if [ -f /etc/systemd/system/arcadely.service ]; then
#    sudo systemctl stop arcadely.service
#    sudo systemctl disable arcadely.service
#else
#    sudo \cp -f ./arcadely.service /etc/systemd/system/arcadely.service
#fi

# TODO: adjust path
sudo ln -sf ~/spox/qrd/qrd.service /etc/systemd/system/qrd.service
sudo systemctl enable qrd.service
sudo systemctl start qrd.service

